export const CATEGORY_ICONS: Record<string, string> = {
  "انتقال فایل": "📁",
  "File Transfer": "📁",
  وب: "🌐",
  Web: "🌐",
  ایمیل: "📧",
  Email: "📧",
  امنیت: "🔒",
  Security: "🔒",
  "دسترسی از راه دور": "🖥️",
  "Remote Access": "🖥️",
  "سرویس‌های شبکه": "🔗",
  "Network Services": "🔗",
  "مدیریت شبکه": "📊",
  "Network Management": "📊",
  دایرکتوری: "📂",
  Directory: "📂",
  "پایگاه داده": "🗄️",
  Database: "🗄️",
  "صف پیام": "📨",
  "Message Queue": "📨",
  "رسانه و ارتباطات": "🎬",
  "Media & Communication": "🎬",
  "اشتراک‌گذاری": "🔄",
  Sharing: "🔄",
  پراکسی: "🛡️",
  Proxy: "🛡️",
  "کانتینر و DevOps": "🐳",
  "Container & DevOps": "🐳",
  مانیتورینگ: "📈",
  Monitoring: "📈",
  "بازی و چندرسانه‌ای": "🎮",
  "Gaming & Multimedia": "🎮",
  "وب‌سرور و API": "⚡",
  "Web Server & API": "⚡",
  چاپ: "🖨️",
  Printing: "🖨️",
  "ذخیره‌سازی": "💾",
  Storage: "💾",
  "CI/CD و ابزارهای توسعه": "🔧",
  "CI/CD & Dev Tools": "🔧",
  "ارتباطات تیمی": "💬",
  "Team Communication": "💬",
  "مجازی‌سازی": "🖥️",
  Virtualization: "🖥️",
};

export const CONTRIBUTE_URLS = {
  fa: "https://github.com/erfanbanaei/netports/issues/new?template=add_protocol_fa.yml",
  en: "https://github.com/erfanbanaei/netports/issues/new?template=add_protocol_en.yml",
} as const;