import "./globals.css";

import { Geist, Geist_Mono } from "next/font/google";

import type { Metadata } from "next";
import localFont from 'next/font/local';

const IranSans = localFont({
  preload: true,
  display: 'swap',
  src: [
    {
      path: '..//../public/fonts/IranSans_Light.ttf',
      weight: '300',
      style: 'normal',
    },
    {
      path: '..//../public/fonts/IranSans.ttf',
      weight: '400',
      style: 'normal',
    },
    {
      path: '..//../public/fonts/IranSans_Medium.ttf',
      weight: '500',
      style: 'normal',
    },
    {
      path: '..//../public/fonts/IranSans_Bold.ttf',
      weight: '700',
      style: 'normal',
    },
  ],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${IranSans.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
